# fly.toml app configuration file generated for misty-sun-229 on 2023-09-14T20:53:22Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "misty-sun-229"
primary_region = "sin"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
